.TH apt-offline 8 "January, 2015" "version 1.6" "USER COMMANDS"
.SH NAME
apt-offline \- Offline APT Package manager
.SH SYNOPSIS
.B apt-offline
[ARGUMENTS] [OPTIONS]

.SH DESCRIPTION
apt-offline brings
offline package management functionality to Debian based system.  It can be
used to download packages and its dependencies to be installed later on (or
required to update) a disconnected machine.  Packages can be downloaded from a
different connected machine.

.PP
It can also fetch bug reports for the packages that are downloaded.
.PP
Unless the \-h/\-v or \-\-help/\-\-version options are given, one of the
.B get, set
or
.B install
commands must be provided.

.SS set FILENAME [-h] [--install-packages PKG...PKG_N] [--install-src-packages PKG...PKG_N] --src-build-dep [--release release_name] [--update] [--upgrade] [--upgrade-type upgrade]

.PP
.B set
generates a signature file with the data required to install on or update the
disconnected machine.

.B FILENAME {apt-offline.sig}
is the signature file generated on the machine. This file will contain all the
information necessary for apt.

.IP "\fB\-\-install\-packages [PKG...PKG_N]\fP" 10
Packages that need to be installed

.IP "\fB\-\-install\-src\-packages [PKG...PKG_N]\fP" 10
Source packages that need to be installed

.IP "\fB\-\-src\-build\-dep\fP" 10
Download Build Dependency packages for the source packages requested

.IP "\fB\-\-release release_name\fP" 10
Release target to install packages from

.IP "\fB\-\-update\fP" 10
Generate APT Database signature for an update. This is the equivalent of using
.B "apt-get update"

.IP "\fB\-\-upgrade\fP" 10
Generate APT Database signature for package upgrade. This is the equivalent of using
.B "apt-get upgrade"

.IP "\fB\-\-upgrade\-type {upgrade_type}\fP" 10
Type of upgrade you would like to perform. Default is
.B "upgrade".
Other valid types are
.B "dist-upgrade" and "dselect-upgrade"

.SS get FILENAME [-h] [--socket-timeout ] [-d / --download-dir] [-s / --cache-dir] [--no-checksum] [-t / --threads ] [--bundle] [--bug-reports] [--proxy-host] [--proxy-port]

.PP

.B get
downloads APT data as per a signature file.

.B FILENAME {apt-offline.sig}
is the signature file required for details about data to be downloaded. This
file should have been generated by the above
.B set
command.

.IP "\fB\-d, \-\-download\-dir DIR_NAME\fP" 10
Download data to the specified DIR_NAME folder. If no folder name is specified, data is downloaded to a folder in the TEMPDIR path in the format
.B apt-offline-download-$PID

.IP "\fB\-s, \-\-cache\-dir DIR_NAME\fP" 10
Look for data in the cache before downloading it from the internet. If you are on a Debian box, you would want to specify
.I /var/cache/apt/archives
here. If the data is not available in the cache, the downloaded data is also copied to the cache.

.IP "\fB\-\-no\-checksum\fP" 10
Enabling this option will bypass the checksum verification of each downloaded file thus losing integrity of the package. Usage of this option is highly discouraged

.IP "\fB\-t, \-\-threads NUM_OF_THREADS\fP" 10
Number of threads to spawn for downloads. Default is 1. Using too many threads can overload the servers, hence it is advisable to keep the number low

.IP "\fB\-\-bundle FILENAME\fP" 10
Create an archive file FILENAME. The file is archived in zip format

.IP "\fB\-\-bug\-reports\fP" 10
Download bug reports for packages that are being downloaded. Currently only
the Debian BTS is supported.

.IP "\fB\-\-proxy\-host\fP" 10
Specify the Proxy Host to be used.

.IP "\fB\-\-proxy\-port\fP" 10
Specify the Proxy port number to be used.

.SS install FILE/FOLDER [-h] [--skip-bug-reports ] [--install-src-path PATH] [--allow-unauthenticated]

.PP

.B install
installs APT data to the APT package database and updates it.

.B FILE {archive_bundle_file}
Install data from the archive (bundle) file.

.B FOLDER {/folder/path}
Install data from the folder path.

Either FILE or FOLDER argument can be provided to the
.B install
command.

.IP "\fB\-\-skip\-bug\-reports\fP" 10
Skip listing of downloaded bug reports, if any.

.IP "\fB\-\-allow\-unauthenticated\fP" 10
Don't verify GPG signatures for the data to be installed to APT. Usage of this option is highly discouraged.

.IP "\fB\-\-install\-src\-path PATH\fP" 10
Path to filesystem where we want the source packages to be installed to. Default will be a folder in your TEMPDIR.

.SH GLOBAL OPTIONS
.TP
\-h, \-\-help
Show help message

.TP
\-\-verbose
Run in verbose mode

.TP
\-\-test\-windows
Developer only. Used for testing on windows

.TP
\-v, \-\-version
Display the version of the program


.SH EXAMPLES
.TP
.B NOTE: argument/option handling
apt\-offline relies on argparse for argument/option parsing. To explicitly instruct apt\-offline about an argument, you can pass it with the \-\- delimiter.

.B Ex. apt\-offline set \-\-update \-\-upgrade \-\-install\-packages wm2 \-\- foo.sig

By specifying the
.B \-\-
delimiter, we instruct apt\-offline that foo.sig is an argument to the 
.B apt\-offline 
command and not to the
.B \-\-install\-packages
option.

Otherwise, you could also use it positionally next to the set command

.B Ex. apt\-offline set foo.sig \-\-update \-\-upgrade \-\-install\-packages wm2

.TP
.B apt-offline set FILENAME
This command will generate a signature file FILENAME for APT Package Database.
To generate only the signature for updates, use the \-\-update option.  To
generate only the signature for package upgrades, use the \-\-upgrade option.
Default behavior when no options are specified is to generate a signature for
both the operations.

.TP
.B apt-offline get FILENAME
This command will fetch the data required for APT Package Database as per the
signature file FILENAME generated by
.B apt-offline get.
To download bug reports also use the \-\-bug\-reports option.  Currently supported bug tracker is Debian BTS only.
By default, if neither of \-d or \-\-bundle options are specified, apt-offline downloads data into a folder inside the TEMPDIR environment folder in the format apt\-offline\-downloads\-PID, where PID is the PID of the running apt\-offline process. Example on a linux machine would be something like: /tmp/apt-offline-downloads-23242/

.TP
.B apt-offline install FILE|FOLDER
This command will sync the data downloaded by
.B apt-offline get
to the APT Package Database and update it.
Depending on where the data was downloaded to or packed into, either the
absolute FOLDER path or the archive FILE path can be specified.

.TP
The following sequence of commands will keep a machine up to date, with the package lists one step ahead of the upgrade:
.B apt-offline set foo.sig \-\-upgrade \-\-update
Requests the packages needed to upgrade the machine, based on the current package lists. Also, requests the new package lists for the next update.

.B apt-offline get foo.sig -d FOLDER
Downloads the packages for upgrading the machine, along with the package lists for the next time apt-offline set \-\-upgrade is run.

.B apt-offline install FOLDER/FILE
Positions the packages for the upgrade, along with new the package lists.

.B apt-get upgrade
Upgrades to the state of the earlier package lists.

.B NOTE:
On a freshly installed box, that was installed without the network, the package database is null. In that case, you first need to run 
.B apt-offline 
with just the 
.B \-\-update 
option to ensure you have a meaningful package database

.SH AUTHOR
.B apt-offline is written by Ritesh Raj Sarraf (rrs@researchut.com)

If you wish to report a bug in apt-offline, please see 
.B http://apt-offline.alioth.debian.org
or send an email to me at
.B rrs@researchut.com

.SH SEE ALSO
apt-get(8),
apt-cache(8),
dpkg(8),
aptitude(8),

.SH DEDICATION
This software is dedicated to the memory of my father Santosh Kumar Sarraf. We miss you a lot.
