#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# apt-offline
#
############################################################################
#    Copyright (C) 2010 Manish Sinha                                       #
#    mail@manishsinha.net                                                  #
#                                                                          #
#    This program is free software; you can redistribute it and/or modify  #
#    it under the terms of the GNU General Public License as published by  #
#    the Free Software Foundation; either version 3 of the License, or     #
#    (at your option) any later version.                                   #
#                                                                          #
#    This program is distributed in the hope that it will be useful,       #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#    GNU General Public License for more details.                          #
#                                                                          #
#    You should have received a copy of the GNU General Public License     #
#    along with this program; if not, write to the                         #
#    Free Software Foundation, Inc.,                                       #
#    59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
############################################################################

import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from apt_offline_gui.AptOfflineQtMain import AptOfflineQtMain

try:
    # This seems to be needed, at least of Debian
    os.putenv('QT_X11_NO_MITSHM', "1")
except:
    sys.stderr.write("Couldn't set environment variable\n")



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    myapp = AptOfflineQtMain()
    myapp.show()
    sys.exit(app.exec_())

