Document: apt-offline
Title: Debian apt-offline Manual
Author: <insert document author here>
Abstract: This manual describes what apt-offline is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/apt-offline/apt-offline.sgml.gz

Format: postscript
Files: /usr/share/doc/apt-offline/apt-offline.ps.gz

Format: text
Files: /usr/share/doc/apt-offline/apt-offline.text.gz

Format: HTML
Index: /usr/share/doc/apt-offline/html/index.html
Files: /usr/share/doc/apt-offline/html/*.html
