# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AptOfflineQtAbout.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutAptOffline(object):
    def setupUi(self, AboutAptOffline):
        AboutAptOffline.setObjectName("AboutAptOffline")
        AboutAptOffline.setWindowModality(QtCore.Qt.ApplicationModal)
        AboutAptOffline.resize(526, 378)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutAptOffline.sizePolicy().hasHeightForWidth())
        AboutAptOffline.setSizePolicy(sizePolicy)
        AboutAptOffline.setMinimumSize(QtCore.QSize(526, 378))
        AboutAptOffline.setMaximumSize(QtCore.QSize(526, 378))
        self.label = QtWidgets.QLabel(AboutAptOffline)
        self.label.setGeometry(QtCore.QRect(12, 30, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(AboutAptOffline)
        self.tabWidget.setGeometry(QtCore.QRect(7, 90, 510, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.aboutTab = QtWidgets.QWidget()
        self.aboutTab.setObjectName("aboutTab")
        self.label_3 = QtWidgets.QLabel(self.aboutTab)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 491, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_14 = QtWidgets.QLabel(self.aboutTab)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 481, 111))
        self.label_14.setScaledContents(True)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.aboutTab, "")
        self.authorTab = QtWidgets.QWidget()
        self.authorTab.setObjectName("authorTab")
        self.label_4 = QtWidgets.QLabel(self.authorTab)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.authorTab)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 271, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.authorTab)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.authorTab)
        self.label_7.setGeometry(QtCore.QRect(30, 80, 261, 16))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.authorTab)
        self.label_8.setGeometry(QtCore.QRect(30, 100, 271, 16))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_15 = QtWidgets.QLabel(self.authorTab)
        self.label_15.setGeometry(QtCore.QRect(30, 120, 280, 20))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.authorTab, "")
        self.thanksTab = QtWidgets.QWidget()
        self.thanksTab.setObjectName("thanksTab")
        self.label_9 = QtWidgets.QLabel(self.thanksTab)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 221, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.thanksTab)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.thanksTab)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 161, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.thanksTab)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 161, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.thanksTab)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 471, 51))
        self.label_13.setScaledContents(True)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.thanksTab, "")
        self.licenseTab = QtWidgets.QWidget()
        self.licenseTab.setObjectName("licenseTab")
        self.licenseText = QtWidgets.QPlainTextEdit(self.licenseTab)
        self.licenseText.setGeometry(QtCore.QRect(4, 4, 490, 203))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.licenseText.setFont(font)
        self.licenseText.setAcceptDrops(False)
        self.licenseText.setTabChangesFocus(True)
        self.licenseText.setUndoRedoEnabled(False)
        self.licenseText.setReadOnly(True)
        self.licenseText.setObjectName("licenseText")
        self.tabWidget.addTab(self.licenseTab, "")
        self.label_2 = QtWidgets.QLabel(AboutAptOffline)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 511, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(AboutAptOffline)
        self.pushButton.setGeometry(QtCore.QRect(416, 340, 101, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/dialog-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(AboutAptOffline)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(AboutAptOffline.close)
        QtCore.QMetaObject.connectSlotsByName(AboutAptOffline)
        AboutAptOffline.setTabOrder(self.tabWidget, self.licenseText)
        AboutAptOffline.setTabOrder(self.licenseText, self.pushButton)

    def retranslateUi(self, AboutAptOffline):
        _translate = QtCore.QCoreApplication.translate
        AboutAptOffline.setWindowTitle(_translate("AboutAptOffline", "About Apt-Offline"))
        self.label.setText(_translate("AboutAptOffline", "Apt-Offline"))
        self.label_3.setText(_translate("AboutAptOffline", "apt-offline is an Offline APT Package Manager for Debian and derivatives. "))
        self.label_14.setText(_translate("AboutAptOffline", "apt-offline can fully update/upgrade your disconnected Debian box without the need of connecting it to the network.  \n"
"\n"
"This is a Graphical User Interface which exposes the functionality of apt-offline."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aboutTab), _translate("AboutAptOffline", "About"))
        self.label_4.setText(_translate("AboutAptOffline", "Written by:"))
        self.label_5.setText(_translate("AboutAptOffline", "Ritesh Raj Sarraf <rrs@researchut.com>"))
        self.label_6.setText(_translate("AboutAptOffline", "GUI written by:"))
        self.label_7.setText(_translate("AboutAptOffline", "Manish Sinha <mail@manishsinha.net>"))
        self.label_8.setText(_translate("AboutAptOffline", "Abhishek Mishra <ideamonk@gmail.com>"))
        self.label_15.setText(_translate("AboutAptOffline", "Ritesh Raj Sarraf <rrs@researchut.com>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.authorTab), _translate("AboutAptOffline", "Author"))
        self.label_9.setText(_translate("AboutAptOffline", "Peter Otten"))
        self.label_10.setText(_translate("AboutAptOffline", "Duncan Booth"))
        self.label_11.setText(_translate("AboutAptOffline", "Simon Forman"))
        self.label_12.setText(_translate("AboutAptOffline", "Dennis Lee Bieber"))
        self.label_13.setText(_translate("AboutAptOffline", "The awesome Directi people for their office space required for the mini hackfests"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.thanksTab), _translate("AboutAptOffline", "Thanks To"))
        self.licenseText.setPlainText(_translate("AboutAptOffline", "                    GNU GENERAL PUBLIC LICENSE\n"
"                       Version 3, 29 June 2007\n"
"\n"
" Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>\n"
" Everyone is permitted to copy and distribute verbatim copies\n"
" of this license document, but changing it is not allowed.\n"
"\n"
"\n"
"apt-offline is Copyright (C) - Ritesh Raj Sarraf"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.licenseTab), _translate("AboutAptOffline", "License"))
        self.label_2.setText(_translate("AboutAptOffline", "A GUI for apt-offline - an offline APT Package Manager"))
        self.pushButton.setText(_translate("AboutAptOffline", "Close"))

from . import resources_rc
