# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AptOfflineQtInstall.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AptOfflineQtInstall(object):
    def setupUi(self, AptOfflineQtInstall):
        AptOfflineQtInstall.setObjectName("AptOfflineQtInstall")
        AptOfflineQtInstall.setWindowModality(QtCore.Qt.ApplicationModal)
        AptOfflineQtInstall.resize(466, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AptOfflineQtInstall.sizePolicy().hasHeightForWidth())
        AptOfflineQtInstall.setSizePolicy(sizePolicy)
        AptOfflineQtInstall.setMinimumSize(QtCore.QSize(466, 400))
        AptOfflineQtInstall.setMaximumSize(QtCore.QSize(466, 400))
        self.zipFilePath = QtWidgets.QLineEdit(AptOfflineQtInstall)
        self.zipFilePath.setGeometry(QtCore.QRect(8, 32, 310, 30))
        self.zipFilePath.setObjectName("zipFilePath")
        self.browseFilePathButton = QtWidgets.QPushButton(AptOfflineQtInstall)
        self.browseFilePathButton.setGeometry(QtCore.QRect(340, 32, 110, 30))
        self.browseFilePathButton.setObjectName("browseFilePathButton")
        self.startInstallButton = QtWidgets.QPushButton(AptOfflineQtInstall)
        self.startInstallButton.setEnabled(False)
        self.startInstallButton.setGeometry(QtCore.QRect(340, 110, 110, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/dialog-ok-apply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startInstallButton.setIcon(icon)
        self.startInstallButton.setObjectName("startInstallButton")
        self.cancelButton = QtWidgets.QPushButton(AptOfflineQtInstall)
        self.cancelButton.setGeometry(QtCore.QRect(340, 70, 110, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon1)
        self.cancelButton.setObjectName("cancelButton")
        self.statusProgressBar = QtWidgets.QProgressBar(AptOfflineQtInstall)
        self.statusProgressBar.setGeometry(QtCore.QRect(8, 146, 440, 20))
        self.statusProgressBar.setProperty("value", 0)
        self.statusProgressBar.setObjectName("statusProgressBar")
        self.label = QtWidgets.QLabel(AptOfflineQtInstall)
        self.label.setGeometry(QtCore.QRect(8, 2, 190, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AptOfflineQtInstall)
        self.label_2.setGeometry(QtCore.QRect(12, 120, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.progressStatusDescription = QtWidgets.QLabel(AptOfflineQtInstall)
        self.progressStatusDescription.setGeometry(QtCore.QRect(68, 120, 53, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressStatusDescription.setFont(font)
        self.progressStatusDescription.setObjectName("progressStatusDescription")
        self.rawLogHolder = QtWidgets.QTextEdit(AptOfflineQtInstall)
        self.rawLogHolder.setGeometry(QtCore.QRect(8, 180, 441, 200))
        self.rawLogHolder.setTabChangesFocus(True)
        self.rawLogHolder.setUndoRedoEnabled(False)
        self.rawLogHolder.setReadOnly(True)
        self.rawLogHolder.setAcceptRichText(False)
        self.rawLogHolder.setObjectName("rawLogHolder")
        self.bugReportsButton = QtWidgets.QPushButton(AptOfflineQtInstall)
        self.bugReportsButton.setEnabled(False)
        self.bugReportsButton.setGeometry(QtCore.QRect(10, 75, 130, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/help-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bugReportsButton.setIcon(icon2)
        self.bugReportsButton.setObjectName("bugReportsButton")
        self.browseFileFoldercheckBox = QtWidgets.QCheckBox(AptOfflineQtInstall)
        self.browseFileFoldercheckBox.setGeometry(QtCore.QRect(342, 10, 110, 18))
        self.browseFileFoldercheckBox.setObjectName("browseFileFoldercheckBox")
        self.changelogButton = QtWidgets.QPushButton(AptOfflineQtInstall)
        self.changelogButton.setEnabled(False)
        self.changelogButton.setGeometry(QtCore.QRect(170, 75, 140, 30))
        self.changelogButton.setIcon(icon2)
        self.changelogButton.setObjectName("changelogButton")

        self.retranslateUi(AptOfflineQtInstall)
        QtCore.QMetaObject.connectSlotsByName(AptOfflineQtInstall)
        AptOfflineQtInstall.setTabOrder(self.zipFilePath, self.browseFileFoldercheckBox)
        AptOfflineQtInstall.setTabOrder(self.browseFileFoldercheckBox, self.browseFilePathButton)
        AptOfflineQtInstall.setTabOrder(self.browseFilePathButton, self.bugReportsButton)
        AptOfflineQtInstall.setTabOrder(self.bugReportsButton, self.changelogButton)
        AptOfflineQtInstall.setTabOrder(self.changelogButton, self.cancelButton)
        AptOfflineQtInstall.setTabOrder(self.cancelButton, self.startInstallButton)
        AptOfflineQtInstall.setTabOrder(self.startInstallButton, self.rawLogHolder)

    def retranslateUi(self, AptOfflineQtInstall):
        _translate = QtCore.QCoreApplication.translate
        AptOfflineQtInstall.setWindowTitle(_translate("AptOfflineQtInstall", "Install Packages"))
        self.browseFilePathButton.setText(_translate("AptOfflineQtInstall", "Browse"))
        self.startInstallButton.setText(_translate("AptOfflineQtInstall", "Install"))
        self.cancelButton.setText(_translate("AptOfflineQtInstall", "Close"))
        self.label.setText(_translate("AptOfflineQtInstall", "Specify file or folder path"))
        self.label_2.setText(_translate("AptOfflineQtInstall", "Status:"))
        self.progressStatusDescription.setText(_translate("AptOfflineQtInstall", "Ready"))
        self.bugReportsButton.setText(_translate("AptOfflineQtInstall", "Bug Reports"))
        self.browseFileFoldercheckBox.setText(_translate("AptOfflineQtInstall", "Is Directory"))
        self.changelogButton.setToolTip(_translate("AptOfflineQtInstall", "Display Changelog"))
        self.changelogButton.setText(_translate("AptOfflineQtInstall", "Changelog"))

import resources_rc
