# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AptOfflineQtFetch.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AptOfflineQtFetch(object):
    def setupUi(self, AptOfflineQtFetch):
        AptOfflineQtFetch.setObjectName("AptOfflineQtFetch")
        AptOfflineQtFetch.setWindowModality(QtCore.Qt.ApplicationModal)
        AptOfflineQtFetch.resize(468, 483)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AptOfflineQtFetch.sizePolicy().hasHeightForWidth())
        AptOfflineQtFetch.setSizePolicy(sizePolicy)
        AptOfflineQtFetch.setMinimumSize(QtCore.QSize(468, 475))
        AptOfflineQtFetch.setMaximumSize(QtCore.QSize(468, 495))
        self.profileFilePath = QtWidgets.QLineEdit(AptOfflineQtFetch)
        self.profileFilePath.setGeometry(QtCore.QRect(30, 35, 270, 30))
        self.profileFilePath.setClearButtonEnabled(True)
        self.profileFilePath.setObjectName("profileFilePath")
        self.browseFilePathButton = QtWidgets.QPushButton(AptOfflineQtFetch)
        self.browseFilePathButton.setGeometry(QtCore.QRect(320, 35, 110, 30))
        self.browseFilePathButton.setObjectName("browseFilePathButton")
        self.startDownloadButton = QtWidgets.QPushButton(AptOfflineQtFetch)
        self.startDownloadButton.setEnabled(False)
        self.startDownloadButton.setGeometry(QtCore.QRect(179, 148, 120, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/go-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startDownloadButton.setIcon(icon)
        self.startDownloadButton.setShortcut("")
        self.startDownloadButton.setCheckable(False)
        self.startDownloadButton.setChecked(False)
        self.startDownloadButton.setFlat(False)
        self.startDownloadButton.setObjectName("startDownloadButton")
        self.cancelButton = QtWidgets.QPushButton(AptOfflineQtFetch)
        self.cancelButton.setGeometry(QtCore.QRect(319, 148, 110, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon1)
        self.cancelButton.setObjectName("cancelButton")
        self.lblSelectSig = QtWidgets.QLabel(AptOfflineQtFetch)
        self.lblSelectSig.setGeometry(QtCore.QRect(30, 5, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSelectSig.setFont(font)
        self.lblSelectSig.setObjectName("lblSelectSig")
        self.statusProgressBar = QtWidgets.QProgressBar(AptOfflineQtFetch)
        self.statusProgressBar.setGeometry(QtCore.QRect(30, 214, 410, 20))
        self.statusProgressBar.setProperty("value", 0)
        self.statusProgressBar.setObjectName("statusProgressBar")
        self.lblStatus = QtWidgets.QLabel(AptOfflineQtFetch)
        self.lblStatus.setGeometry(QtCore.QRect(32, 194, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblStatus.setFont(font)
        self.lblStatus.setObjectName("lblStatus")
        self.progressStatusDescription = QtWidgets.QLabel(AptOfflineQtFetch)
        self.progressStatusDescription.setGeometry(QtCore.QRect(82, 194, 341, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressStatusDescription.setFont(font)
        self.progressStatusDescription.setObjectName("progressStatusDescription")
        self.rawLogHolder = QtWidgets.QTextEdit(AptOfflineQtFetch)
        self.rawLogHolder.setGeometry(QtCore.QRect(30, 252, 411, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rawLogHolder.setFont(font)
        self.rawLogHolder.setAcceptDrops(False)
        self.rawLogHolder.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.rawLogHolder.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.rawLogHolder.setUndoRedoEnabled(False)
        self.rawLogHolder.setReadOnly(True)
        self.rawLogHolder.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>")
        self.rawLogHolder.setTabStopWidth(80)
        self.rawLogHolder.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.rawLogHolder.setObjectName("rawLogHolder")
        self.browseZipFileButton = QtWidgets.QPushButton(AptOfflineQtFetch)
        self.browseZipFileButton.setGeometry(QtCore.QRect(320, 98, 110, 30))
        self.browseZipFileButton.setObjectName("browseZipFileButton")
        self.lblSaveAs = QtWidgets.QLabel(AptOfflineQtFetch)
        self.lblSaveAs.setGeometry(QtCore.QRect(30, 68, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSaveAs.setFont(font)
        self.lblSaveAs.setObjectName("lblSaveAs")
        self.zipFilePath = QtWidgets.QLineEdit(AptOfflineQtFetch)
        self.zipFilePath.setGeometry(QtCore.QRect(30, 98, 270, 30))
        self.zipFilePath.setClearButtonEnabled(True)
        self.zipFilePath.setObjectName("zipFilePath")
        self.advancedOptionsButton = QtWidgets.QPushButton(AptOfflineQtFetch)
        self.advancedOptionsButton.setEnabled(True)
        self.advancedOptionsButton.setGeometry(QtCore.QRect(31, 148, 120, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.advancedOptionsButton.setIcon(icon2)
        self.advancedOptionsButton.setShortcut("")
        self.advancedOptionsButton.setCheckable(False)
        self.advancedOptionsButton.setChecked(False)
        self.advancedOptionsButton.setFlat(False)
        self.advancedOptionsButton.setObjectName("advancedOptionsButton")
        self.saveDatacheckBox = QtWidgets.QCheckBox(AptOfflineQtFetch)
        self.saveDatacheckBox.setGeometry(QtCore.QRect(321, 80, 110, 18))
        self.saveDatacheckBox.setObjectName("saveDatacheckBox")

        self.retranslateUi(AptOfflineQtFetch)
        QtCore.QMetaObject.connectSlotsByName(AptOfflineQtFetch)
        AptOfflineQtFetch.setTabOrder(self.profileFilePath, self.browseFilePathButton)
        AptOfflineQtFetch.setTabOrder(self.browseFilePathButton, self.zipFilePath)
        AptOfflineQtFetch.setTabOrder(self.zipFilePath, self.saveDatacheckBox)
        AptOfflineQtFetch.setTabOrder(self.saveDatacheckBox, self.browseZipFileButton)
        AptOfflineQtFetch.setTabOrder(self.browseZipFileButton, self.advancedOptionsButton)
        AptOfflineQtFetch.setTabOrder(self.advancedOptionsButton, self.startDownloadButton)
        AptOfflineQtFetch.setTabOrder(self.startDownloadButton, self.cancelButton)
        AptOfflineQtFetch.setTabOrder(self.cancelButton, self.rawLogHolder)

    def retranslateUi(self, AptOfflineQtFetch):
        _translate = QtCore.QCoreApplication.translate
        AptOfflineQtFetch.setWindowTitle(_translate("AptOfflineQtFetch", "Fetch Packages or Updates"))
        self.profileFilePath.setToolTip(_translate("AptOfflineQtFetch", "Path to signature file"))
        self.browseFilePathButton.setText(_translate("AptOfflineQtFetch", "Browse"))
        self.startDownloadButton.setToolTip(_translate("AptOfflineQtFetch", "Start download"))
        self.startDownloadButton.setText(_translate("AptOfflineQtFetch", "Download"))
        self.cancelButton.setToolTip(_translate("AptOfflineQtFetch", "Close window"))
        self.cancelButton.setText(_translate("AptOfflineQtFetch", "Close"))
        self.lblSelectSig.setText(_translate("AptOfflineQtFetch", "Select the signature file"))
        self.lblStatus.setText(_translate("AptOfflineQtFetch", "Status:"))
        self.progressStatusDescription.setText(_translate("AptOfflineQtFetch", "Ready"))
        self.browseZipFileButton.setText(_translate("AptOfflineQtFetch", "Browse"))
        self.lblSaveAs.setText(_translate("AptOfflineQtFetch", "Save data as"))
        self.zipFilePath.setToolTip(_translate("AptOfflineQtFetch", "Data save location file/directory"))
        self.advancedOptionsButton.setToolTip(_translate("AptOfflineQtFetch", "Additional options for download"))
        self.advancedOptionsButton.setText(_translate("AptOfflineQtFetch", "Options"))
        self.saveDatacheckBox.setToolTip(_translate("AptOfflineQtFetch", "Click if target save location is a directory"))
        self.saveDatacheckBox.setText(_translate("AptOfflineQtFetch", "Is Directory"))

import resources_rc
