# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AptOfflineQtFetchOptions.ui'
#
# Created: Sat Dec 29 02:30:59 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_downloadOptionsDialog(object):
    def setupUi(self, downloadOptionsDialog):
        downloadOptionsDialog.setObjectName(_fromUtf8("downloadOptionsDialog"))
        downloadOptionsDialog.resize(443, 304)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(downloadOptionsDialog.sizePolicy().hasHeightForWidth())
        downloadOptionsDialog.setSizePolicy(sizePolicy)
        downloadOptionsDialog.setMinimumSize(QtCore.QSize(443, 304))
        downloadOptionsDialog.setMaximumSize(QtCore.QSize(443, 304))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/configure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        downloadOptionsDialog.setWindowIcon(icon)
        downloadOptionsDialog.setSizeGripEnabled(False)
        downloadOptionsDialog.setModal(True)
        self.lblThreads = QtGui.QLabel(downloadOptionsDialog)
        self.lblThreads.setGeometry(QtCore.QRect(300, 10, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblThreads.setFont(font)
        self.lblThreads.setObjectName(_fromUtf8("lblThreads"))
        self.spinThreads = QtGui.QSpinBox(downloadOptionsDialog)
        self.spinThreads.setGeometry(QtCore.QRect(390, 9, 40, 30))
        self.spinThreads.setMinimum(1)
        self.spinThreads.setMaximum(10)
        self.spinThreads.setObjectName(_fromUtf8("spinThreads"))
        self.downloadOptionDialogOkButton = QtGui.QPushButton(downloadOptionsDialog)
        self.downloadOptionDialogOkButton.setGeometry(QtCore.QRect(350, 260, 81, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/dialog-ok-apply.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadOptionDialogOkButton.setIcon(icon1)
        self.downloadOptionDialogOkButton.setObjectName(_fromUtf8("downloadOptionDialogOkButton"))
        self.lblSocketTimeo = QtGui.QLabel(downloadOptionsDialog)
        self.lblSocketTimeo.setGeometry(QtCore.QRect(10, 8, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSocketTimeo.setFont(font)
        self.lblSocketTimeo.setObjectName(_fromUtf8("lblSocketTimeo"))
        self.spinTimeout = QtGui.QSpinBox(downloadOptionsDialog)
        self.spinTimeout.setGeometry(QtCore.QRect(150, 7, 51, 30))
        self.spinTimeout.setMinimum(10)
        self.spinTimeout.setMaximum(100)
        self.spinTimeout.setProperty("value", 30)
        self.spinTimeout.setObjectName(_fromUtf8("spinTimeout"))
        self.lblTmpDownload = QtGui.QLabel(downloadOptionsDialog)
        self.lblTmpDownload.setGeometry(QtCore.QRect(10, 50, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblTmpDownload.setFont(font)
        self.lblTmpDownload.setObjectName(_fromUtf8("lblTmpDownload"))
        self.tempDirLineEdit = QtGui.QLineEdit(downloadOptionsDialog)
        self.tempDirLineEdit.setGeometry(QtCore.QRect(150, 50, 191, 31))
        self.tempDirLineEdit.setObjectName(_fromUtf8("tempDirLineEdit"))
        self.tempDirBrowseButton = QtGui.QPushButton(downloadOptionsDialog)
        self.tempDirBrowseButton.setGeometry(QtCore.QRect(350, 50, 81, 31))
        self.tempDirBrowseButton.setObjectName(_fromUtf8("tempDirBrowseButton"))
        self.cacheDirLineEdit = QtGui.QLineEdit(downloadOptionsDialog)
        self.cacheDirLineEdit.setGeometry(QtCore.QRect(150, 90, 191, 31))
        self.cacheDirLineEdit.setObjectName(_fromUtf8("cacheDirLineEdit"))
        self.cacheDirBrowseButton = QtGui.QPushButton(downloadOptionsDialog)
        self.cacheDirBrowseButton.setGeometry(QtCore.QRect(350, 90, 81, 31))
        self.cacheDirBrowseButton.setObjectName(_fromUtf8("cacheDirBrowseButton"))
        self.lblCacheDir = QtGui.QLabel(downloadOptionsDialog)
        self.lblCacheDir.setGeometry(QtCore.QRect(10, 90, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCacheDir.setFont(font)
        self.lblCacheDir.setObjectName(_fromUtf8("lblCacheDir"))
        self.disableChecksumCheckBox = QtGui.QCheckBox(downloadOptionsDialog)
        self.disableChecksumCheckBox.setGeometry(QtCore.QRect(10, 130, 151, 31))
        self.disableChecksumCheckBox.setObjectName(_fromUtf8("disableChecksumCheckBox"))
        self.fetchBugReportsCheckBox = QtGui.QCheckBox(downloadOptionsDialog)
        self.fetchBugReportsCheckBox.setGeometry(QtCore.QRect(180, 130, 151, 31))
        self.fetchBugReportsCheckBox.setObjectName(_fromUtf8("fetchBugReportsCheckBox"))
        self.proxyGroupBox = QtGui.QGroupBox(downloadOptionsDialog)
        self.proxyGroupBox.setGeometry(QtCore.QRect(10, 170, 441, 80))
        self.proxyGroupBox.setStyleSheet(_fromUtf8(""))
        self.proxyGroupBox.setTitle(_fromUtf8(""))
        self.proxyGroupBox.setFlat(True)
        self.proxyGroupBox.setObjectName(_fromUtf8("proxyGroupBox"))
        self.proxyHostLineEdit = QtGui.QLineEdit(self.proxyGroupBox)
        self.proxyHostLineEdit.setEnabled(False)
        self.proxyHostLineEdit.setGeometry(QtCore.QRect(25, 36, 238, 31))
        self.proxyHostLineEdit.setObjectName(_fromUtf8("proxyHostLineEdit"))
        self.proxyPortLineEdit = QtGui.QLineEdit(self.proxyGroupBox)
        self.proxyPortLineEdit.setEnabled(False)
        self.proxyPortLineEdit.setGeometry(QtCore.QRect(280, 36, 61, 31))
        self.proxyPortLineEdit.setText(_fromUtf8(""))
        self.proxyPortLineEdit.setObjectName(_fromUtf8("proxyPortLineEdit"))
        self.useProxyCheckBox = QtGui.QCheckBox(self.proxyGroupBox)
        self.useProxyCheckBox.setGeometry(QtCore.QRect(0, 0, 89, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.useProxyCheckBox.setFont(font)
        self.useProxyCheckBox.setObjectName(_fromUtf8("useProxyCheckBox"))
        self.lblProxyPort = QtGui.QLabel(downloadOptionsDialog)
        self.lblProxyPort.setGeometry(QtCore.QRect(290, 186, 138, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblProxyPort.setFont(font)
        self.lblProxyPort.setObjectName(_fromUtf8("lblProxyPort"))
        self.lblProxyHost = QtGui.QLabel(downloadOptionsDialog)
        self.lblProxyHost.setGeometry(QtCore.QRect(35, 186, 138, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblProxyHost.setFont(font)
        self.lblProxyHost.setObjectName(_fromUtf8("lblProxyHost"))

        self.retranslateUi(downloadOptionsDialog)
        QtCore.QMetaObject.connectSlotsByName(downloadOptionsDialog)

    def retranslateUi(self, downloadOptionsDialog):
        downloadOptionsDialog.setWindowTitle(QtGui.QApplication.translate("downloadOptionsDialog", "Advanced options for download", None, QtGui.QApplication.UnicodeUTF8))
        self.lblThreads.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Number of parallel connections", None, QtGui.QApplication.UnicodeUTF8))
        self.lblThreads.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Use threads", None, QtGui.QApplication.UnicodeUTF8))
        self.spinThreads.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Number of parallel connections", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadOptionDialogOkButton.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSocketTimeo.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Nework timeout in seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSocketTimeo.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Network Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.spinTimeout.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Nework timeout in seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTmpDownload.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Temporary download directory", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTmpDownload.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Temporary Download", None, QtGui.QApplication.UnicodeUTF8))
        self.tempDirLineEdit.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Temporary download directory", None, QtGui.QApplication.UnicodeUTF8))
        self.tempDirBrowseButton.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheDirLineEdit.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Cache folder to search for", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheDirBrowseButton.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCacheDir.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Cache folder to search for", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCacheDir.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Cache Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.disableChecksumCheckBox.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Disables checksum verification of downloaded items. Enable only if you know what you are doing", None, QtGui.QApplication.UnicodeUTF8))
        self.disableChecksumCheckBox.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Disable Checksum", None, QtGui.QApplication.UnicodeUTF8))
        self.fetchBugReportsCheckBox.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Fetch Bug Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.fetchBugReportsCheckBox.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Fetch Bug Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.proxyHostLineEdit.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Proxy Server Host/IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.proxyPortLineEdit.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Proxy Server Port Address", None, QtGui.QApplication.UnicodeUTF8))
        self.useProxyCheckBox.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxyPort.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Cache folder to search for", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxyPort.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxyHost.setToolTip(QtGui.QApplication.translate("downloadOptionsDialog", "Cache folder to search for", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxyHost.setText(QtGui.QApplication.translate("downloadOptionsDialog", "Host", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
